/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bean.Carro;
import Model.Bean.Cliente;
import Model.DAO.ClienteDAO;
import Model.DAO.PesquisaCarroDAO;
import Model.DAO.PesquisaClienteDAO;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro Melo
 */
public class AlugarCarro extends javax.swing.JInternalFrame {

    /**
     * Creates new form PesquisaCliente
     */
    public AlugarCarro() {
        initComponents();
        readTableCliente();
        readTableCarDisp();
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void readTableCliente() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        modelo.setNumRows(0);
        ClienteDAO cliDAO = new ClienteDAO();

        for (Cliente cli : cliDAO.read()) {

            modelo.addRow(new Object[]{
                cli.getId(),
                cli.getNome(),
                cli.getEndereco(),
                cli.getTelefone(),
                cli.getCelular(),
                cli.getDtNasc(),
                cli.getRg(),
                cli.getCpf(),
                cli.getEmail(),
            });

        }
    }
    public void readTableCarDisp() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaCarros.getModel();
        modelo.setNumRows(0);
        PesquisaCarroDAO pesqDAO = new PesquisaCarroDAO();

        for (Carro car : pesqDAO.carrosDisponiveis()) {

            modelo.addRow(new Object[]{
                car.getId(),
                car.getFabricante(),
                car.getModelo(),
                car.getCor(),
                car.getMotor(),
                car.getTpCombustivel(),
                car.getKmAtual(),
                car.getDtCadastro(),
                car.getAlugado(),
                car.getDtAluguel(),
                car.getDtDevolucao(),
            });

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        painel5 = new javax.swing.JPanel();
        label_clicad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botao_cancelar = new javax.swing.JButton();
        botao_alugar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        label_info = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCarros = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("ALUGAR CARRO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N

        tabelaClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "ENDEREÇO", "TELEFONE", "CELULAR", "DT NASC.", "RG", "CPF", "E-MAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaClientes);
        if (tabelaClientes.getColumnModel().getColumnCount() > 0) {
            tabelaClientes.getColumnModel().getColumn(0).setMinWidth(25);
            tabelaClientes.getColumnModel().getColumn(0).setPreferredWidth(25);
            tabelaClientes.getColumnModel().getColumn(0).setMaxWidth(25);
            tabelaClientes.getColumnModel().getColumn(3).setMinWidth(90);
            tabelaClientes.getColumnModel().getColumn(3).setPreferredWidth(90);
            tabelaClientes.getColumnModel().getColumn(3).setMaxWidth(90);
            tabelaClientes.getColumnModel().getColumn(4).setMinWidth(70);
            tabelaClientes.getColumnModel().getColumn(4).setPreferredWidth(70);
            tabelaClientes.getColumnModel().getColumn(4).setMaxWidth(70);
            tabelaClientes.getColumnModel().getColumn(5).setMinWidth(100);
            tabelaClientes.getColumnModel().getColumn(5).setPreferredWidth(100);
            tabelaClientes.getColumnModel().getColumn(5).setMaxWidth(100);
            tabelaClientes.getColumnModel().getColumn(6).setMinWidth(120);
            tabelaClientes.getColumnModel().getColumn(6).setPreferredWidth(120);
            tabelaClientes.getColumnModel().getColumn(6).setMaxWidth(120);
            tabelaClientes.getColumnModel().getColumn(7).setMinWidth(100);
            tabelaClientes.getColumnModel().getColumn(7).setPreferredWidth(100);
            tabelaClientes.getColumnModel().getColumn(7).setMaxWidth(100);
            tabelaClientes.getColumnModel().getColumn(8).setMinWidth(120);
            tabelaClientes.getColumnModel().getColumn(8).setPreferredWidth(120);
            tabelaClientes.getColumnModel().getColumn(8).setMaxWidth(120);
        }

        painel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label_clicad.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        label_clicad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_clicad.setText("Alugar Carro");

        javax.swing.GroupLayout painel5Layout = new javax.swing.GroupLayout(painel5);
        painel5.setLayout(painel5Layout);
        painel5Layout.setHorizontalGroup(
            painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_clicad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painel5Layout.setVerticalGroup(
            painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(label_clicad)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botao_cancelar.setText("Fechar");
        botao_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelarActionPerformed(evt);
            }
        });

        botao_alugar.setText("Alugar");
        botao_alugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botao_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(botao_alugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_alugar)
                .addGap(288, 288, 288)
                .addComponent(botao_cancelar)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label_info.setText("Para alugar um carro selecione o cliente na lista, depois o carro desejado e em seguida clique em alugar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_info, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        tabelaCarros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FABRICANTE", "MODELO", "COR", "MOTOR", "COMBUSTIVEL", "KILOMETRAGEM", "DT CADASTRO", "ALUGADO", "DT ALUGUEL", "DT DEVOLUCAO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaCarros);
        if (tabelaCarros.getColumnModel().getColumnCount() > 0) {
            tabelaCarros.getColumnModel().getColumn(0).setMinWidth(25);
            tabelaCarros.getColumnModel().getColumn(0).setPreferredWidth(25);
            tabelaCarros.getColumnModel().getColumn(0).setMaxWidth(25);
            tabelaCarros.getColumnModel().getColumn(3).setMinWidth(90);
            tabelaCarros.getColumnModel().getColumn(3).setPreferredWidth(90);
            tabelaCarros.getColumnModel().getColumn(3).setMaxWidth(90);
            tabelaCarros.getColumnModel().getColumn(4).setMinWidth(70);
            tabelaCarros.getColumnModel().getColumn(4).setPreferredWidth(70);
            tabelaCarros.getColumnModel().getColumn(4).setMaxWidth(70);
            tabelaCarros.getColumnModel().getColumn(5).setMinWidth(100);
            tabelaCarros.getColumnModel().getColumn(5).setPreferredWidth(100);
            tabelaCarros.getColumnModel().getColumn(5).setMaxWidth(100);
            tabelaCarros.getColumnModel().getColumn(6).setMinWidth(120);
            tabelaCarros.getColumnModel().getColumn(6).setPreferredWidth(120);
            tabelaCarros.getColumnModel().getColumn(6).setMaxWidth(120);
            tabelaCarros.getColumnModel().getColumn(7).setMinWidth(100);
            tabelaCarros.getColumnModel().getColumn(7).setPreferredWidth(100);
            tabelaCarros.getColumnModel().getColumn(7).setMaxWidth(100);
            tabelaCarros.getColumnModel().getColumn(8).setMinWidth(120);
            tabelaCarros.getColumnModel().getColumn(8).setPreferredWidth(120);
            tabelaCarros.getColumnModel().getColumn(8).setMaxWidth(120);
            tabelaCarros.getColumnModel().getColumn(9).setMinWidth(120);
            tabelaCarros.getColumnModel().getColumn(9).setPreferredWidth(120);
            tabelaCarros.getColumnModel().getColumn(9).setMaxWidth(120);
            tabelaCarros.getColumnModel().getColumn(10).setMinWidth(120);
            tabelaCarros.getColumnModel().getColumn(10).setPreferredWidth(120);
            tabelaCarros.getColumnModel().getColumn(10).setMaxWidth(120);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botao_cancelarActionPerformed

    private void botao_alugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alugarActionPerformed
//        verificando seleção na tabela clientes     verificando selação na tabela carros   
        if (tabelaClientes.getSelectedRow() != -1 && tabelaCarros.getSelectedRow() != -1) {
//            System.out.println("Linha selecionada: " + tabelaClientes.getSelectedRow());
//            System.out.println("ID da linha selecionada: " + Integer.parseInt(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(),0).toString()));

            ConfirmaAluguel confALu = new ConfirmaAluguel();
            TelaPrincipal.jDesktopPane1.add(confALu);
            confALu.setVisible(true);
            confALu.setPosicao();

            Cliente cliente = new Cliente();
            PesquisaClienteDAO pesCliDao = new PesquisaClienteDAO();
            cliente = pesCliDao.readCli(Integer.parseInt(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 0).toString()));
            
            ConfirmaAluguel.campo_nome.setText(cliente.getNome());
            ConfirmaAluguel.campo_endereco.setText(cliente.getEndereco());
            ConfirmaAluguel.campo_identidade.setText(cliente.getRg());
            ConfirmaAluguel.campo_cpf.setText(cliente.getCpf());
            ConfirmaAluguel.campo_telefone.setText(cliente.getTelefone());
            ConfirmaAluguel.campo_celular.setText(cliente.getCelular());
            ConfirmaAluguel.campo_email.setText(cliente.getEmail());
            ConfirmaAluguel.campo_dtNasc.setText(cliente.getDtNasc());
            ConfirmaAluguel.campo_idCli.setText(Integer.toString(cliente.getId()));
            ConfirmaAluguel.campo_idCli.setVisible(false);
            
            Carro carro = new Carro();
            PesquisaCarroDAO pesCarDao = new PesquisaCarroDAO();
            carro = pesCarDao.readCar(Integer.parseInt(tabelaCarros.getValueAt(tabelaCarros.getSelectedRow(), 0).toString()));
            Date dataSistema = new Date();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            
            ConfirmaAluguel.campo_fabricante.setText(carro.getFabricante());
            ConfirmaAluguel.campo_modelo.setText(carro.getModelo());
            ConfirmaAluguel.campo_cor.setText(carro.getCor());
            ConfirmaAluguel.campo_tpComb.setText(carro.getTpCombustivel());
            ConfirmaAluguel.campo_motor.setText(carro.getMotor());
            ConfirmaAluguel.campo_km.setText(carro.getKmAtual());
            ConfirmaAluguel.campo_dtAluguel.setText(formato.format(dataSistema));
            ConfirmaAluguel.campo_idCar.setText(Integer.toString(carro.getId()));
            ConfirmaAluguel.campo_idCar.setVisible(false);

            this.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente e um carro para prosseguir..");
        }
    }//GEN-LAST:event_botao_alugarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_alugar;
    private javax.swing.JButton botao_cancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_clicad;
    private javax.swing.JLabel label_info;
    private javax.swing.JPanel painel5;
    private javax.swing.JTable tabelaCarros;
    private javax.swing.JTable tabelaClientes;
    // End of variables declaration//GEN-END:variables
}
