/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bean.Carro;
import Model.DAO.CarroDAO;
import java.awt.Dimension;

/**
 *
 * @author Leandro Melo
 */
public class CadastroCarros extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroCarros
     */
    public CadastroCarros() {
        initComponents();
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_principal = new javax.swing.JPanel();
        botao_cancelar = new javax.swing.JButton();
        label_titulo = new javax.swing.JLabel();
        label_fabricante = new javax.swing.JLabel();
        label_modelo = new javax.swing.JLabel();
        label_tpComb = new javax.swing.JLabel();
        label_cor = new javax.swing.JLabel();
        campo_fabricante = new javax.swing.JTextField();
        campo_tpModelo = new javax.swing.JTextField();
        label_motor = new javax.swing.JLabel();
        label_km = new javax.swing.JLabel();
        campo_km = new javax.swing.JFormattedTextField();
        label_dtCadastro = new javax.swing.JLabel();
        campo_dtCadastro = new javax.swing.JFormattedTextField();
        label_image = new javax.swing.JLabel();
        campo_cor = new javax.swing.JTextField();
        campo_tpComb = new javax.swing.JTextField();
        campo_motor = new javax.swing.JFormattedTextField();
        botao_ok = new javax.swing.JButton();

        setTitle("CADASTRAR CARRO");

        botao_cancelar.setText("Cancelar");
        botao_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelarActionPerformed(evt);
            }
        });

        label_titulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        label_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_titulo.setText("CADASTRAR CARRO");
        label_titulo.setToolTipText("");

        label_fabricante.setText("FABRICANTE");

        label_modelo.setText("MODELO");

        label_tpComb.setText("TIPO DE COMBUSTÍVEL");

        label_cor.setText("COR");

        label_motor.setText("MOTOR");

        label_km.setText("KILOMETRAGEM");

        try {
            campo_km.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###,00 KM")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_km.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        label_dtCadastro.setText("DATA DE CADASTRO");

        campo_dtCadastro.setEditable(false);
        try {
            campo_dtCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_dtCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        label_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icone_cadastro_carro.png"))); // NOI18N
        label_image.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        try {
            campo_motor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_motor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        botao_ok.setText("OK");
        botao_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_principalLayout = new javax.swing.GroupLayout(painel_principal);
        painel_principal.setLayout(painel_principalLayout);
        painel_principalLayout.setHorizontalGroup(
            painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_principalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botao_ok)
                        .addGap(18, 18, 18)
                        .addComponent(botao_cancelar))
                    .addComponent(label_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painel_principalLayout.createSequentialGroup()
                        .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campo_tpModelo)
                            .addComponent(campo_fabricante)
                            .addComponent(label_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_fabricante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(painel_principalLayout.createSequentialGroup()
                                .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painel_principalLayout.createSequentialGroup()
                                        .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(label_cor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(label_motor, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                            .addComponent(campo_cor))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(painel_principalLayout.createSequentialGroup()
                                        .addComponent(campo_motor, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                        .addGap(71, 71, 71)))
                                .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo_km)
                                    .addComponent(label_km, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_tpComb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campo_tpComb)))
                            .addComponent(label_dtCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campo_dtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(label_image)
                        .addGap(40, 40, 40)))
                .addContainerGap())
        );
        painel_principalLayout.setVerticalGroup(
            painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_principalLayout.createSequentialGroup()
                .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(label_fabricante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_principalLayout.createSequentialGroup()
                        .addComponent(campo_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_modelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_tpModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_cor)
                            .addComponent(label_tpComb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campo_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_tpComb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_motor)
                            .addComponent(label_km))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campo_km, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_motor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_dtCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_dtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(label_image, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                .addGap(188, 188, 188)
                .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_cancelar)
                    .addComponent(botao_ok))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botao_cancelarActionPerformed

    private void botao_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_okActionPerformed
        Carro carro = new Carro();
        CarroDAO cliDAO = new CarroDAO();

        carro.setFabricante(campo_fabricante.getText());
        carro.setModelo(campo_tpModelo.getText());
        carro.setCor(campo_cor.getText());
        carro.setMotor(campo_motor.getText());
        carro.setTpCombustivel(campo_tpComb.getText());
        carro.setDtCadastro(campo_dtCadastro.getText());
        carro.setKmAtual(campo_km.getText());
        

        cliDAO.create(carro);

        campo_fabricante.setText("");
        campo_tpModelo.setText("");
        campo_cor.setText("");
        campo_motor.setText("");
        campo_tpComb.setText("");
    //    campo_dtCadastro.setText("");
        campo_km.setText("");
    }//GEN-LAST:event_botao_okActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cancelar;
    private javax.swing.JButton botao_ok;
    private javax.swing.JTextField campo_cor;
    public static javax.swing.JFormattedTextField campo_dtCadastro;
    private javax.swing.JTextField campo_fabricante;
    private javax.swing.JFormattedTextField campo_km;
    private javax.swing.JFormattedTextField campo_motor;
    private javax.swing.JTextField campo_tpComb;
    private javax.swing.JTextField campo_tpModelo;
    private javax.swing.JLabel label_cor;
    private javax.swing.JLabel label_dtCadastro;
    private javax.swing.JLabel label_fabricante;
    private javax.swing.JLabel label_image;
    private javax.swing.JLabel label_km;
    private javax.swing.JLabel label_modelo;
    private javax.swing.JLabel label_motor;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_tpComb;
    private javax.swing.JPanel painel_principal;
    // End of variables declaration//GEN-END:variables
}
