/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bean.Carro;
import Model.DAO.CarroDAO;
import Model.DAO.PesquisaCarroDAO;
import java.awt.Dimension;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro Melo
 */
public class PesquisaCarros extends javax.swing.JInternalFrame {

    /**
     * Creates new form PesquisaCliente
     */
    public PesquisaCarros() {
        initComponents();
        readTable();
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void readTable() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaCarros.getModel();
        modelo.setNumRows(0);
        CarroDAO carDAO = new CarroDAO();

        for (Carro car : carDAO.read()) {

            modelo.addRow(new Object[]{
                car.getId(),
                car.getFabricante(),
                car.getModelo(),
                car.getCor(),
                car.getMotor(),
                car.getTpCombustivel(),
                car.getKmAtual(),
                car.getDtCadastro(),
                car.getAlugado(),
                car.getDtAluguel(),
                car.getDtDevolucao(),
            });

        }
    }
    
    public void readAlugados() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaCarros.getModel();
        modelo.setNumRows(0);
        PesquisaCarroDAO pesqDAO = new PesquisaCarroDAO();

        for (Carro car : pesqDAO.carrosAlugados()) {

            modelo.addRow(new Object[]{
                car.getId(),
                car.getFabricante(),
                car.getModelo(),
                car.getCor(),
                car.getMotor(),
                car.getTpCombustivel(),
                car.getKmAtual(),
                car.getDtCadastro(),
                car.getAlugado(),
                car.getDtAluguel(),
                car.getDtDevolucao(),
            });

        }
    }
    
    public void readDisponiveis() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaCarros.getModel();
        modelo.setNumRows(0);
        PesquisaCarroDAO pesqCarDAO = new PesquisaCarroDAO();

        for (Carro car : pesqCarDAO.carrosDisponiveis()) {

            modelo.addRow(new Object[]{
                car.getId(),
                car.getFabricante(),
                car.getModelo(),
                car.getCor(),
                car.getMotor(),
                car.getTpCombustivel(),
                car.getKmAtual(),
                car.getDtCadastro(),
                car.getAlugado(),
                car.getDtAluguel(),
                car.getDtDevolucao(),
            });

        }
    }
public void readForFabricante(String fabric) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaCarros.getModel();
        modelo.setNumRows(0);
        PesquisaCarroDAO pesqCarDAO = new PesquisaCarroDAO();

        for (Carro car : pesqCarDAO.searchForFabricante(fabric)) {

            modelo.addRow(new Object[]{
                car.getId(),
                car.getFabricante(),
                car.getModelo(),
                car.getCor(),
                car.getMotor(),
                car.getTpCombustivel(),
                car.getKmAtual(),
                car.getDtCadastro(),
                car.getAlugado(),
                car.getDtAluguel(),
                car.getDtDevolucao(),
            });

        }
    }
    public void readForModelo(String modCar) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaCarros.getModel();
        modelo.setNumRows(0);
        PesquisaCarroDAO pesqCarDAO = new PesquisaCarroDAO();

        for (Carro car : pesqCarDAO.searchForModelo(modCar)) {

            modelo.addRow(new Object[]{
                car.getId(),
                car.getFabricante(),
                car.getModelo(),
                car.getCor(),
                car.getMotor(),
                car.getTpCombustivel(),
                car.getKmAtual(),
                car.getDtCadastro(),
                car.getAlugado(),
                car.getDtAluguel(),
                car.getDtDevolucao(),
            });

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCarros = new javax.swing.JTable();
        painel5 = new javax.swing.JPanel();
        label_cadcar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botao_cancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        botao_alugados = new javax.swing.JButton();
        botao_disponivel = new javax.swing.JButton();
        botao_todos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        campo_fabric = new javax.swing.JTextField();
        label_fabric = new javax.swing.JLabel();
        label_modelo = new javax.swing.JLabel();
        campo_modelo = new javax.swing.JTextField();
        label_fabricante = new javax.swing.JLabel();
        label_codigo = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_telefone = new javax.swing.JLabel();
        campo_cor = new javax.swing.JTextField();
        campo_codigo = new javax.swing.JTextField();
        campo_telefone = new javax.swing.JTextField();
        campo_email = new javax.swing.JTextField();
        botao_pesFone = new javax.swing.JButton();
        botao_pesMod = new javax.swing.JButton();
        botao_pesFabric = new javax.swing.JButton();
        botao_pesFabr = new javax.swing.JButton();
        botao_pesMail = new javax.swing.JButton();
        botao_pesCod = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("CARROS CADASTRADOS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N

        tabelaCarros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FABRICANTE", "MODELO", "COR", "MOTOR", "COMBUSTIVEL", "KILOMETRAGEM", "DT CADASTRO", "ALUGADO", "DT ALUGUEL", "DT DEVOLUCAO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaCarros);
        if (tabelaCarros.getColumnModel().getColumnCount() > 0) {
            tabelaCarros.getColumnModel().getColumn(0).setMinWidth(25);
            tabelaCarros.getColumnModel().getColumn(0).setPreferredWidth(25);
            tabelaCarros.getColumnModel().getColumn(0).setMaxWidth(25);
            tabelaCarros.getColumnModel().getColumn(3).setMinWidth(90);
            tabelaCarros.getColumnModel().getColumn(3).setPreferredWidth(90);
            tabelaCarros.getColumnModel().getColumn(3).setMaxWidth(90);
            tabelaCarros.getColumnModel().getColumn(4).setMinWidth(70);
            tabelaCarros.getColumnModel().getColumn(4).setPreferredWidth(70);
            tabelaCarros.getColumnModel().getColumn(4).setMaxWidth(70);
            tabelaCarros.getColumnModel().getColumn(5).setMinWidth(100);
            tabelaCarros.getColumnModel().getColumn(5).setPreferredWidth(100);
            tabelaCarros.getColumnModel().getColumn(5).setMaxWidth(100);
            tabelaCarros.getColumnModel().getColumn(6).setMinWidth(120);
            tabelaCarros.getColumnModel().getColumn(6).setPreferredWidth(120);
            tabelaCarros.getColumnModel().getColumn(6).setMaxWidth(120);
            tabelaCarros.getColumnModel().getColumn(7).setMinWidth(100);
            tabelaCarros.getColumnModel().getColumn(7).setPreferredWidth(100);
            tabelaCarros.getColumnModel().getColumn(7).setMaxWidth(100);
            tabelaCarros.getColumnModel().getColumn(8).setMinWidth(120);
            tabelaCarros.getColumnModel().getColumn(8).setPreferredWidth(120);
            tabelaCarros.getColumnModel().getColumn(8).setMaxWidth(120);
            tabelaCarros.getColumnModel().getColumn(9).setMinWidth(120);
            tabelaCarros.getColumnModel().getColumn(9).setPreferredWidth(120);
            tabelaCarros.getColumnModel().getColumn(9).setMaxWidth(120);
            tabelaCarros.getColumnModel().getColumn(10).setMinWidth(120);
            tabelaCarros.getColumnModel().getColumn(10).setPreferredWidth(120);
            tabelaCarros.getColumnModel().getColumn(10).setMaxWidth(120);
        }

        painel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label_cadcar.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        label_cadcar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_cadcar.setText("Carros Cadastrados");

        javax.swing.GroupLayout painel5Layout = new javax.swing.GroupLayout(painel5);
        painel5.setLayout(painel5Layout);
        painel5Layout.setHorizontalGroup(
            painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_cadcar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painel5Layout.setVerticalGroup(
            painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(label_cadcar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botao_cancelar.setText("Fechar");
        botao_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botao_alugados.setText("Alugados");
        botao_alugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alugadosActionPerformed(evt);
            }
        });

        botao_disponivel.setText("Disponíveis");
        botao_disponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_disponivelActionPerformed(evt);
            }
        });

        botao_todos.setText("Todos");
        botao_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_todosActionPerformed(evt);
            }
        });

        jLabel1.setText("Mostrar Carros:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botao_alugados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botao_disponivel, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
            .addComponent(botao_todos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_alugados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_disponivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_todos)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botao_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(botao_cancelar)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("PESQUISA"));

        campo_fabric.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_fabricKeyPressed(evt);
            }
        });

        label_fabric.setText("FABRICANTE");

        label_modelo.setText("MODELO");

        campo_modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_modeloKeyPressed(evt);
            }
        });

        label_fabricante.setText("COR");

        label_codigo.setText("COMBUSTIVEL");

        label_email.setText("-");

        label_telefone.setText("-");

        campo_cor.setEditable(false);
        campo_cor.setEnabled(false);
        campo_cor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_corKeyPressed(evt);
            }
        });

        campo_codigo.setEditable(false);
        campo_codigo.setEnabled(false);
        campo_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_codigoKeyPressed(evt);
            }
        });

        campo_telefone.setEditable(false);
        campo_telefone.setEnabled(false);
        campo_telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_telefoneKeyPressed(evt);
            }
        });

        campo_email.setEditable(false);
        campo_email.setEnabled(false);
        campo_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_emailKeyPressed(evt);
            }
        });

        botao_pesFone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        botao_pesFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesFoneActionPerformed(evt);
            }
        });
        botao_pesFone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao_pesFoneKeyPressed(evt);
            }
        });

        botao_pesMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        botao_pesMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesModActionPerformed(evt);
            }
        });
        botao_pesMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao_pesModKeyPressed(evt);
            }
        });

        botao_pesFabric.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        botao_pesFabric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesFabricActionPerformed(evt);
            }
        });
        botao_pesFabric.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao_pesFabricKeyPressed(evt);
            }
        });

        botao_pesFabr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        botao_pesFabr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesFabrActionPerformed(evt);
            }
        });
        botao_pesFabr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao_pesFabrKeyPressed(evt);
            }
        });

        botao_pesMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        botao_pesMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesMailActionPerformed(evt);
            }
        });
        botao_pesMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao_pesMailKeyPressed(evt);
            }
        });

        botao_pesCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        botao_pesCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesCodActionPerformed(evt);
            }
        });
        botao_pesCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao_pesCodKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_fabric)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campo_fabric, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao_pesFabric, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(campo_modelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_pesMod, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campo_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_pesFabr, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campo_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_pesCod, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campo_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_pesFone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_telefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campo_email, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_pesMail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_email))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_modelo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label_fabric))
                    .addComponent(label_telefone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_email, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_fabricante)
                        .addComponent(label_codigo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao_pesFone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botao_pesFabr, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botao_pesMail, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botao_pesCod, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(campo_fabric, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campo_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campo_modelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_pesFabric, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botao_pesMod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(campo_cor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botao_cancelarActionPerformed

    private void botao_pesFabricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesFabricActionPerformed

        readForFabricante(campo_fabric.getText());

    }//GEN-LAST:event_botao_pesFabricActionPerformed

    private void botao_pesFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesFoneActionPerformed

//        readForTelefone(campo_telefone.getText());

    }//GEN-LAST:event_botao_pesFoneActionPerformed

    private void botao_pesModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesModActionPerformed
        
        readForModelo(campo_modelo.getText());
        
    }//GEN-LAST:event_botao_pesModActionPerformed

    private void botao_pesFabrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesFabrActionPerformed

//        readForFabricante(campo_fabricante.getText());

    }//GEN-LAST:event_botao_pesFabrActionPerformed

    private void botao_pesMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesMailActionPerformed

//        readForEmail(campo_email.getText());

    }//GEN-LAST:event_botao_pesMailActionPerformed

    private void botao_pesCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesCodActionPerformed

//        readForCodigo(campo_codigo.getText());

    }//GEN-LAST:event_botao_pesCodActionPerformed

    private void campo_fabricKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_fabricKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER && campo_fabric.getText().isEmpty()) {
            campo_modelo.requestFocus();
        } else if (evt.getKeyCode() == evt.VK_ENTER && !campo_fabric.getText().isEmpty()) {
            readForFabricante(campo_fabric.getText());
            campo_fabric.selectAll();
        } else if (evt.getKeyCode() == evt.VK_DELETE && campo_fabric.getText().isEmpty()) {
            readTable();
        } else if (evt.getKeyCode() == evt.VK_DELETE) {
            readTable();
        }
    }//GEN-LAST:event_campo_fabricKeyPressed

    private void botao_pesFabricKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao_pesFabricKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_pesFabricKeyPressed

    private void campo_modeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_modeloKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER && campo_modelo.getText().isEmpty()) {
            campo_cor.requestFocus();
        } else if (evt.getKeyCode() == evt.VK_ENTER && !campo_modelo.getText().isEmpty()) {
            readForModelo(campo_modelo.getText());
            campo_modelo.selectAll();
        } else if (evt.getKeyCode() == evt.VK_DELETE && campo_modelo.getText().isEmpty()) {
            readTable();
        } else if (evt.getKeyCode() == evt.VK_DELETE) {
            readTable();
        }
    }//GEN-LAST:event_campo_modeloKeyPressed

    private void botao_pesModKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao_pesModKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_pesModKeyPressed

    private void campo_corKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_corKeyPressed
/*        if (evt.getKeyCode() == evt.VK_ENTER && campo_fabricante.getText().isEmpty()) {
            campo_codigo.requestFocus();
        } else if (evt.getKeyCode() == evt.VK_ENTER && !campo_fabricante.getText().isEmpty()) {
            readForFabricante(campo_fabricante.getText());
            campo_fabricante.selectAll();
        } else if (evt.getKeyCode() == evt.VK_DELETE && campo_fabricante.getText().isEmpty()) {
            readTable();
        } else if (evt.getKeyCode() == evt.VK_DELETE) {
            readTable();
        }*/
    }//GEN-LAST:event_campo_corKeyPressed

    private void botao_pesFabrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao_pesFabrKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_pesFabrKeyPressed

    private void campo_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_codigoKeyPressed
/*        if (evt.getKeyCode() == evt.VK_ENTER && campo_codigo.getText().isEmpty()) {
            campo_telefone.requestFocus();
        } else if (evt.getKeyCode() == evt.VK_ENTER && !campo_codigo.getText().isEmpty()) {
            readForCodigo(campo_codigo.getText());
            campo_codigo.selectAll();
        } else if (evt.getKeyCode() == evt.VK_DELETE && campo_codigo.getText().isEmpty()) {
            readTable();
        } else if (evt.getKeyCode() == evt.VK_DELETE) {
            readTable();
        }*/
    }//GEN-LAST:event_campo_codigoKeyPressed

    private void botao_pesCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao_pesCodKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_pesCodKeyPressed

    private void campo_telefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_telefoneKeyPressed
/*        if (evt.getKeyCode() == evt.VK_ENTER && campo_telefone.getText().isEmpty()) {
            campo_email.requestFocus();
        } else if (evt.getKeyCode() == evt.VK_ENTER && !campo_telefone.getText().isEmpty()) {
            readForTelefone(campo_telefone.getText());
            campo_telefone.selectAll();
        } else if (evt.getKeyCode() == evt.VK_DELETE && campo_telefone.getText().isEmpty()) {
            readTable();
        } else if (evt.getKeyCode() == evt.VK_DELETE) {
            readTable();
        }*/
    }//GEN-LAST:event_campo_telefoneKeyPressed

    private void botao_pesFoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao_pesFoneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_pesFoneKeyPressed

    private void campo_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_emailKeyPressed
/*        if (evt.getKeyCode() == evt.VK_ENTER && campo_email.getText().isEmpty()) {
            campo_nome.requestFocus();
        } else if (evt.getKeyCode() == evt.VK_ENTER && !campo_email.getText().isEmpty()) {
            readForEmail(campo_email.getText());
            campo_email.selectAll();
        } else if (evt.getKeyCode() == evt.VK_DELETE && campo_email.getText().isEmpty()) {
            readTable();
        } else if (evt.getKeyCode() == evt.VK_DELETE) {
            readTable();
        }*/
    }//GEN-LAST:event_campo_emailKeyPressed

    private void botao_pesMailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao_pesMailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_pesMailKeyPressed

    private void botao_alugadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alugadosActionPerformed
        readAlugados();
        label_cadcar.setText("Carros Alugados");
    }//GEN-LAST:event_botao_alugadosActionPerformed

    private void botao_disponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_disponivelActionPerformed
        readDisponiveis();
        label_cadcar.setText("Carros Disponíveis");
    }//GEN-LAST:event_botao_disponivelActionPerformed

    private void botao_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_todosActionPerformed
        readTable();
        label_cadcar.setText("Carros Cadastrados");
    }//GEN-LAST:event_botao_todosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_alugados;
    private javax.swing.JButton botao_cancelar;
    private javax.swing.JButton botao_disponivel;
    private javax.swing.JButton botao_pesCod;
    private javax.swing.JButton botao_pesFabr;
    private javax.swing.JButton botao_pesFabric;
    private javax.swing.JButton botao_pesFone;
    private javax.swing.JButton botao_pesMail;
    private javax.swing.JButton botao_pesMod;
    private javax.swing.JButton botao_todos;
    private javax.swing.JTextField campo_codigo;
    private javax.swing.JTextField campo_cor;
    private javax.swing.JTextField campo_email;
    private javax.swing.JTextField campo_fabric;
    private javax.swing.JTextField campo_modelo;
    private javax.swing.JTextField campo_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_cadcar;
    private javax.swing.JLabel label_codigo;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_fabric;
    private javax.swing.JLabel label_fabricante;
    private javax.swing.JLabel label_modelo;
    private javax.swing.JLabel label_telefone;
    private javax.swing.JPanel painel5;
    private javax.swing.JTable tabelaCarros;
    // End of variables declaration//GEN-END:variables
}
