/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bean.Cliente;
import Model.DAO.ClienteDAO;
import java.awt.Dimension;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro Melo
 */
public class PesquisaClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form PesquisaCliente
     */
    public PesquisaClientes() {
        initComponents();
        readTable();
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void readTable() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        modelo.setNumRows(0);
        ClienteDAO cliDAO = new ClienteDAO();

        for (Cliente cli : cliDAO.read()) {

            modelo.addRow(new Object[]{
                cli.getId(),
                cli.getNome(),
                cli.getEndereco(),
                cli.getTelefone(),
                cli.getCelular(),
                cli.getDtNasc(),
                cli.getRg(),
                cli.getCpf(),
                cli.getEmail(),
            });

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        painel5 = new javax.swing.JPanel();
        label_clicad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botao_cancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        campo_nome = new javax.swing.JTextField();
        label_nome = new javax.swing.JLabel();
        label_produto = new javax.swing.JLabel();
        campo_produto = new javax.swing.JTextField();
        label_fabricante = new javax.swing.JLabel();
        label_codigo = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_telefone = new javax.swing.JLabel();
        campo_fabricante = new javax.swing.JTextField();
        campo_codigo = new javax.swing.JTextField();
        campo_telefone = new javax.swing.JTextField();
        campo_email = new javax.swing.JTextField();
        botao_pesFone = new javax.swing.JButton();
        botao_pesProd = new javax.swing.JButton();
        botao_pesNome = new javax.swing.JButton();
        botao_pesFabr = new javax.swing.JButton();
        botao_pesMail = new javax.swing.JButton();
        botao_pesCod = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("CLIENTES CADASTRADOS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N

        tabelaClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "ENDEREÇO", "TELEFONE", "CELULAR", "DT NASC.", "RG", "CPF", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaClientes);
        if (tabelaClientes.getColumnModel().getColumnCount() > 0) {
            tabelaClientes.getColumnModel().getColumn(0).setMinWidth(25);
            tabelaClientes.getColumnModel().getColumn(0).setPreferredWidth(25);
            tabelaClientes.getColumnModel().getColumn(0).setMaxWidth(25);
            tabelaClientes.getColumnModel().getColumn(1).setMinWidth(200);
            tabelaClientes.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabelaClientes.getColumnModel().getColumn(1).setMaxWidth(200);
            tabelaClientes.getColumnModel().getColumn(2).setMinWidth(250);
            tabelaClientes.getColumnModel().getColumn(2).setPreferredWidth(250);
            tabelaClientes.getColumnModel().getColumn(2).setMaxWidth(250);
            tabelaClientes.getColumnModel().getColumn(3).setMinWidth(120);
            tabelaClientes.getColumnModel().getColumn(3).setPreferredWidth(120);
            tabelaClientes.getColumnModel().getColumn(3).setMaxWidth(120);
            tabelaClientes.getColumnModel().getColumn(4).setMinWidth(120);
            tabelaClientes.getColumnModel().getColumn(4).setPreferredWidth(120);
            tabelaClientes.getColumnModel().getColumn(4).setMaxWidth(120);
            tabelaClientes.getColumnModel().getColumn(5).setMinWidth(100);
            tabelaClientes.getColumnModel().getColumn(5).setPreferredWidth(100);
            tabelaClientes.getColumnModel().getColumn(5).setMaxWidth(100);
            tabelaClientes.getColumnModel().getColumn(6).setMinWidth(90);
            tabelaClientes.getColumnModel().getColumn(6).setPreferredWidth(90);
            tabelaClientes.getColumnModel().getColumn(6).setMaxWidth(90);
            tabelaClientes.getColumnModel().getColumn(7).setMinWidth(100);
            tabelaClientes.getColumnModel().getColumn(7).setPreferredWidth(100);
            tabelaClientes.getColumnModel().getColumn(7).setMaxWidth(100);
            tabelaClientes.getColumnModel().getColumn(8).setMinWidth(200);
            tabelaClientes.getColumnModel().getColumn(8).setPreferredWidth(200);
            tabelaClientes.getColumnModel().getColumn(8).setMaxWidth(200);
        }

        painel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label_clicad.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        label_clicad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_clicad.setText("Clientes Cadastrados");

        javax.swing.GroupLayout painel5Layout = new javax.swing.GroupLayout(painel5);
        painel5.setLayout(painel5Layout);
        painel5Layout.setHorizontalGroup(
            painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_clicad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painel5Layout.setVerticalGroup(
            painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label_clicad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botao_cancelar.setText("Fechar");
        botao_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botao_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(384, Short.MAX_VALUE)
                .addComponent(botao_cancelar)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("PESQUISA"));

        campo_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_nomeKeyPressed(evt);
            }
        });

        label_nome.setText("NOME");

        label_produto.setText("CPF");

        campo_produto.setEditable(false);
        campo_produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_produtoKeyPressed(evt);
            }
        });

        label_fabricante.setText("RG");

        label_codigo.setText("CELULAR");

        label_email.setText("E-MAIL");

        label_telefone.setText("TELEFONE");

        campo_fabricante.setEditable(false);
        campo_fabricante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_fabricanteKeyPressed(evt);
            }
        });

        campo_codigo.setEditable(false);
        campo_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_codigoKeyPressed(evt);
            }
        });

        campo_telefone.setEditable(false);
        campo_telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_telefoneKeyPressed(evt);
            }
        });

        campo_email.setEditable(false);
        campo_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_emailKeyPressed(evt);
            }
        });

        botao_pesFone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        botao_pesFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesFoneActionPerformed(evt);
            }
        });
        botao_pesFone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao_pesFoneKeyPressed(evt);
            }
        });

        botao_pesProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        botao_pesProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesProdActionPerformed(evt);
            }
        });
        botao_pesProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao_pesProdKeyPressed(evt);
            }
        });

        botao_pesNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        botao_pesNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesNomeActionPerformed(evt);
            }
        });
        botao_pesNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao_pesNomeKeyPressed(evt);
            }
        });

        botao_pesFabr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        botao_pesFabr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesFabrActionPerformed(evt);
            }
        });
        botao_pesFabr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao_pesFabrKeyPressed(evt);
            }
        });

        botao_pesMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        botao_pesMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesMailActionPerformed(evt);
            }
        });
        botao_pesMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao_pesMailKeyPressed(evt);
            }
        });

        botao_pesCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        botao_pesCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesCodActionPerformed(evt);
            }
        });
        botao_pesCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao_pesCodKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nome)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao_pesNome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_produto, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(campo_produto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_pesProd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campo_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_pesFabr, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campo_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_pesCod, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campo_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_pesFone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_telefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campo_email, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_pesMail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_email))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_produto, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label_nome))
                    .addComponent(label_telefone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_email, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_fabricante)
                        .addComponent(label_codigo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao_pesFone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botao_pesFabr, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botao_pesMail, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botao_pesCod, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(campo_nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campo_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campo_produto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_pesNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botao_pesProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(campo_fabricante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botao_cancelarActionPerformed

    private void botao_pesCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao_pesCodKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_pesCodKeyPressed

    private void botao_pesCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesCodActionPerformed

        //        readForCodigo(campo_codigo.getText());
    }//GEN-LAST:event_botao_pesCodActionPerformed

    private void botao_pesMailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao_pesMailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_pesMailKeyPressed

    private void botao_pesMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesMailActionPerformed

        //        readForEmail(campo_email.getText());
    }//GEN-LAST:event_botao_pesMailActionPerformed

    private void botao_pesFabrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao_pesFabrKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_pesFabrKeyPressed

    private void botao_pesFabrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesFabrActionPerformed

        //        readForFabricante(campo_fabricante.getText());
    }//GEN-LAST:event_botao_pesFabrActionPerformed

    private void botao_pesNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao_pesNomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_pesNomeKeyPressed

    private void botao_pesNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesNomeActionPerformed

        //        readForNome(campo_nome.getText());
    }//GEN-LAST:event_botao_pesNomeActionPerformed

    private void botao_pesProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao_pesProdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_pesProdKeyPressed

    private void botao_pesProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesProdActionPerformed

        //        readForProduto(campo_produto.getText());
    }//GEN-LAST:event_botao_pesProdActionPerformed

    private void botao_pesFoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao_pesFoneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_pesFoneKeyPressed

    private void botao_pesFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesFoneActionPerformed

        //        readForTelefone(campo_telefone.getText());
    }//GEN-LAST:event_botao_pesFoneActionPerformed

    private void campo_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_emailKeyPressed
        /*        if (evt.getKeyCode() == evt.VK_ENTER && campo_email.getText().isEmpty()) {
            campo_nome.requestFocus();
        } else if (evt.getKeyCode() == evt.VK_ENTER && !campo_email.getText().isEmpty()) {
            readForEmail(campo_email.getText());
            campo_email.selectAll();
        } else if (evt.getKeyCode() == evt.VK_DELETE && campo_email.getText().isEmpty()) {
            readTable();
        } else if (evt.getKeyCode() == evt.VK_DELETE) {
            readTable();
        }*/
    }//GEN-LAST:event_campo_emailKeyPressed

    private void campo_telefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_telefoneKeyPressed
        /*        if (evt.getKeyCode() == evt.VK_ENTER && campo_telefone.getText().isEmpty()) {
            campo_email.requestFocus();
        } else if (evt.getKeyCode() == evt.VK_ENTER && !campo_telefone.getText().isEmpty()) {
            readForTelefone(campo_telefone.getText());
            campo_telefone.selectAll();
        } else if (evt.getKeyCode() == evt.VK_DELETE && campo_telefone.getText().isEmpty()) {
            readTable();
        } else if (evt.getKeyCode() == evt.VK_DELETE) {
            readTable();
        }*/
    }//GEN-LAST:event_campo_telefoneKeyPressed

    private void campo_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_codigoKeyPressed
        /*        if (evt.getKeyCode() == evt.VK_ENTER && campo_codigo.getText().isEmpty()) {
            campo_telefone.requestFocus();
        } else if (evt.getKeyCode() == evt.VK_ENTER && !campo_codigo.getText().isEmpty()) {
            readForCodigo(campo_codigo.getText());
            campo_codigo.selectAll();
        } else if (evt.getKeyCode() == evt.VK_DELETE && campo_codigo.getText().isEmpty()) {
            readTable();
        } else if (evt.getKeyCode() == evt.VK_DELETE) {
            readTable();
        }*/
    }//GEN-LAST:event_campo_codigoKeyPressed

    private void campo_fabricanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_fabricanteKeyPressed
        /*        if (evt.getKeyCode() == evt.VK_ENTER && campo_fabricante.getText().isEmpty()) {
            campo_codigo.requestFocus();
        } else if (evt.getKeyCode() == evt.VK_ENTER && !campo_fabricante.getText().isEmpty()) {
            readForFabricante(campo_fabricante.getText());
            campo_fabricante.selectAll();
        } else if (evt.getKeyCode() == evt.VK_DELETE && campo_fabricante.getText().isEmpty()) {
            readTable();
        } else if (evt.getKeyCode() == evt.VK_DELETE) {
            readTable();
        }*/
    }//GEN-LAST:event_campo_fabricanteKeyPressed

    private void campo_produtoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_produtoKeyPressed
        /*        if (evt.getKeyCode() == evt.VK_ENTER && campo_produto.getText().isEmpty()) {
            campo_fabricante.requestFocus();
        } else if (evt.getKeyCode() == evt.VK_ENTER && !campo_produto.getText().isEmpty()) {
            readForProduto(campo_produto.getText());
            campo_produto.selectAll();
        } else if (evt.getKeyCode() == evt.VK_DELETE && campo_produto.getText().isEmpty()) {
            readTable();
        } else if (evt.getKeyCode() == evt.VK_DELETE) {
            readTable();
        }*/
    }//GEN-LAST:event_campo_produtoKeyPressed

    private void campo_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_nomeKeyPressed
        /*        if (evt.getKeyCode() == evt.VK_ENTER && campo_nome.getText().isEmpty()) {
            campo_produto.requestFocus();
        } else if (evt.getKeyCode() == evt.VK_ENTER && !campo_nome.getText().isEmpty()) {
            readForNome(campo_nome.getText());
            campo_nome.selectAll();
        } else if (evt.getKeyCode() == evt.VK_DELETE && campo_nome.getText().isEmpty()) {
            readTable();
        } else if (evt.getKeyCode() == evt.VK_DELETE) {
            readTable();
        }*/
    }//GEN-LAST:event_campo_nomeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cancelar;
    private javax.swing.JButton botao_pesCod;
    private javax.swing.JButton botao_pesFabr;
    private javax.swing.JButton botao_pesFone;
    private javax.swing.JButton botao_pesMail;
    private javax.swing.JButton botao_pesNome;
    private javax.swing.JButton botao_pesProd;
    private javax.swing.JTextField campo_codigo;
    private javax.swing.JTextField campo_email;
    private javax.swing.JTextField campo_fabricante;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JTextField campo_produto;
    private javax.swing.JTextField campo_telefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_clicad;
    private javax.swing.JLabel label_codigo;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_fabricante;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_produto;
    private javax.swing.JLabel label_telefone;
    private javax.swing.JPanel painel5;
    private javax.swing.JTable tabelaClientes;
    // End of variables declaration//GEN-END:variables
}
