/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Leandro Melo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_cadastro = new javax.swing.JMenu();
        menu_cadastro_cliente = new javax.swing.JMenuItem();
        menu_cadastro_carro = new javax.swing.JMenuItem();
        menu_alugar = new javax.swing.JMenu();
        menu_alugarCarro = new javax.swing.JMenuItem();
        menu_consulta = new javax.swing.JMenu();
        menu_consulta_cliente = new javax.swing.JMenuItem();
        menu_consulta_carro = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_ajuda = new javax.swing.JMenu();
        menu_ajuda_sobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROJETO AV1");
        setExtendedState(6);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        menu_cadastro.setText("Cadastro");

        menu_cadastro_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menu_cadastro_cliente.setText("Cliente");
        menu_cadastro_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastro_clienteActionPerformed(evt);
            }
        });
        menu_cadastro.add(menu_cadastro_cliente);

        menu_cadastro_carro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        menu_cadastro_carro.setText("Carro");
        menu_cadastro_carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastro_carroActionPerformed(evt);
            }
        });
        menu_cadastro.add(menu_cadastro_carro);

        jMenuBar1.add(menu_cadastro);

        menu_alugar.setText("Alugar");

        menu_alugarCarro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menu_alugarCarro.setText("Alugar Carro");
        menu_alugarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_alugarCarroActionPerformed(evt);
            }
        });
        menu_alugar.add(menu_alugarCarro);

        jMenuBar1.add(menu_alugar);

        menu_consulta.setText("Consulta");

        menu_consulta_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menu_consulta_cliente.setText("Clientes");
        menu_consulta_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_consulta_clienteActionPerformed(evt);
            }
        });
        menu_consulta.add(menu_consulta_cliente);

        menu_consulta_carro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        menu_consulta_carro.setText("Carros");
        menu_consulta_carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_consulta_carroActionPerformed(evt);
            }
        });
        menu_consulta.add(menu_consulta_carro);
        menu_consulta.add(jSeparator1);

        jMenuBar1.add(menu_consulta);

        menu_ajuda.setText("Ajuda");

        menu_ajuda_sobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menu_ajuda_sobre.setText("Sobre");
        menu_ajuda_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ajuda_sobreActionPerformed(evt);
            }
        });
        menu_ajuda.add(menu_ajuda_sobre);

        jMenuBar1.add(menu_ajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_ajuda_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ajuda_sobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_ajuda_sobreActionPerformed

    private void menu_cadastro_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastro_clienteActionPerformed
        CadastroClientes cadCli = new CadastroClientes();
        jDesktopPane1.add(cadCli);
        cadCli.setVisible(true);
        cadCli.setPosicao();
    }//GEN-LAST:event_menu_cadastro_clienteActionPerformed

    private void menu_cadastro_carroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastro_carroActionPerformed
        CadastroCarros cadCar = new CadastroCarros();
        jDesktopPane1.add(cadCar);
        cadCar.setVisible(true);
        cadCar.setPosicao();
        
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        CadastroCarros.campo_dtCadastro.setText(formato.format(dataSistema));
    }//GEN-LAST:event_menu_cadastro_carroActionPerformed

    private void menu_consulta_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_consulta_clienteActionPerformed
        PesquisaClientes pesCli = new PesquisaClientes();
        pesCli.setVisible(true);
        TelaPrincipal.jDesktopPane1.add(pesCli);
        pesCli.setPosicao();
    }//GEN-LAST:event_menu_consulta_clienteActionPerformed

    private void menu_consulta_carroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_consulta_carroActionPerformed
        PesquisaCarros pesCar = new PesquisaCarros();
        pesCar.setVisible(true);
        TelaPrincipal.jDesktopPane1.add(pesCar);
        pesCar.setPosicao();
    }//GEN-LAST:event_menu_consulta_carroActionPerformed

    private void menu_alugarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_alugarCarroActionPerformed
        AlugarCarro aluCar = new AlugarCarro();
        aluCar.setVisible(true);
        TelaPrincipal.jDesktopPane1.add(aluCar);
        aluCar.setPosicao();
    }//GEN-LAST:event_menu_alugarCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menu_ajuda;
    private javax.swing.JMenuItem menu_ajuda_sobre;
    private javax.swing.JMenu menu_alugar;
    private javax.swing.JMenuItem menu_alugarCarro;
    private javax.swing.JMenu menu_cadastro;
    private javax.swing.JMenuItem menu_cadastro_carro;
    private javax.swing.JMenuItem menu_cadastro_cliente;
    private javax.swing.JMenu menu_consulta;
    private javax.swing.JMenuItem menu_consulta_carro;
    private javax.swing.JMenuItem menu_consulta_cliente;
    // End of variables declaration//GEN-END:variables
}
